#!/bin/bash

npm rm \
@types/agenda \
@types/ajv-errors \
@types/async \
@types/body-parser \
@types/chai \
@types/chart.js \
@types/compression \
@types/concurrently \
@types/eslint \
@types/graphql \
@types/hbs \
@types/heremaps \
@types/ioredis \
@types/jest \
@types/jquery \
@types/json2csv \
@types/jsonwebtoken \
@types/lru-cache \
@types/md5 \
@types/mongoose \
@types/mongoose-unique-validator \
@types/morgan \
@types/multer \
@types/node-rsa \
@types/nodemailer \
@types/nodemon \
@types/numeral \
@types/password-hash \
@types/pdfmake \
@types/prettier \
@types/react-email-editor \
@types/redis \
@types/redlock \
@types/sass \
@types/shelljs \
@types/supertest \
@types/swagger-jsdoc \
@types/swagger-ui-express \
@types/winston \
@types/ws \
@typescript-eslint/eslint-plugin \
@typescript-eslint/parser \
autoprefixer \
chai \
concurrently \
cross-env \
eslint \
eslint-config-next \
husky \
inflection \
jest \
nodemon \
postcss \
prettier \
shelljs \
supertest \
ts-jest \
ts-node \
typescript